baseURL = ""
languageCode = "en-us"
title = "ML Studio"
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "What is ML Studio"
  URL = "#what_is"
  weight = 2

  [[menu.header]]
  name = "Features"
  URL = "#features"
  weight = 3

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 4


  [[menu.footer]]
  name = "What is ML Studio"
  URL = "#what_is"
  weight = 2

  [[menu.footer]]
  name = "Features"
  URL = "#features"
  weight = 3

  [[menu.footer]]
  name = "Pricing"
  URL = "#pricing"
  weight = 4

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 5


[params]

  [params.footer]
      copyright = "© 2020 ML Studio. All rights reserved."